### ISSUE TITLE
Update binary build to the latest (0.10.0) thrift release

### ISSUE THREAD

**Issue by dmvolod** [ccascone/mvn-thrift-compiler#1]
Hi Carmelo!

Is there any chance to update this repo to the latest (0.10.0) Thrift release or this is for your personal use only sample?

--
Best regards,
Dmitry

**Comment by ccascone** [comment]
Hi @dmvolod,

Apologies for the late reply. This is most for personal / demo projects use. I think you can just fork this repo and point to that in the pom.xml of your project (using jitpack).

Carmelo
