### ISSUE TITLE
Support for thrift0.11

### ISSUE THREAD

**Issue by MyXOF** [ccascone/mvn-thrift-compiler#3]
Hi, 
Since thrift has upgraded to 0.11.0, can you provide a pre-compiled thrift 0.11 version, or just write a wiki to demonstrate how to generate them manually?

Thanks

**Comment by ccascone** [comment]
Hi unfortunately I don’t have time to generate a new binary and in general to maintain this repo. I stopped using this way of distributing the thrift binary for maven builds a long time ago. I suggest you (or anyone else interested) to fork this repo and update the binary by following the official instructions from thrift.
